INSERT INTO ingredients (category_id, name)
VALUES (1, 'garlic'), (1, 'onion'), (1, 'bell pepper'), (1, 'carrot'), (1, 'scallion'),
(1, 'tomato'),(1, 'potato'), (1, 'red onion'), (1, 'celery'), (1, 'jalapeno'),
(1, 'avocado'), (1, 'shallot'), (1, 'zucchini'), (1, 'cherry tomato'), (1, 'cucumber'),
(1, 'spinach'), (1, 'sweet corn'), (1, 'sweet potato'), (1, 'broccoli'), (1, 'pumpkin'),
(2, 'lemon'), (2, 'lime'), (2, 'apple'), (2, 'orange'), (2, 'banana'),
(2, 'raisins'), (2, 'pineapple'), (2, 'mango'), (2, 'peach'), (2, 'date'),
(2, 'coconut'), (2, 'craisins'), (2, 'pear'), (2, 'grape'), (2, 'pomegranate'),
(2, 'watermelon'), (2, 'strawberry'), (2, 'blueberry'), (2, 'raspberry'), (2, 'cranberry'),
(3, 'butter'), (3, 'egg'), (3, 'milk'), (3, 'heavy cream'), (3, 'sour cream'),
(3, 'buttermilk'), (3, 'yogurt'), (3, 'greek yogurt'), (3, 'cream'), (3, 'whipped cream'),
(3, 'ghee'), (3, 'shortening'), (3, 'condensed milk'), (3, 'half and half'), (3, 'sweetened condensed milk'),
(3, 'parmesan'), (3, 'cream cheese'), (3, 'cheddar'), (3, 'mozzarella'), (3, 'feta'),
(4, 'coconut milk'), (4, 'almond milk'), (4, 'almond butter'), (4, 'tofu'), (4, 'coconut cream'),
(4, 'non-dairy milk'), (4, 'vegan butter'), (4, 'soy milk'), (4, 'extra firm tofu'), (4, 'silken tofu'),
(4, 'kala namak salt'), (4, 'coconut butter'), (4, 'egg replacer'), (4, 'vegan mayonnaise'), (4, 'vegan cheese'),
(4, 'cashew butter'), (4, 'tempeh'), (4, 'coconut yogurt'), (4, 'vegan cream cheese'), (4, 'non-dairy yogurt'),
(5, 'bacon'), (5, 'ground beef'), (5, 'beef steak'), (5, 'ham'), (5, 'sweet italian sausage'),
(5, 'pork loin'), (5, 'prosciutto'), (5, 'sausage'), (5, 'beef roast'), (5, 'ground pork'),
(5, 'proks chops'), (5, 'pepperoni'), (5, 'chicken breast'), (5, 'chicken thighs'), (5, 'ground turkey'),
(5, 'whole chicken'),(5, 'chicken legs'), (5, 'whole turkey'), (5, 'chicken wings'), (5, 'tukey breast'),
(6, 'salmon'), (6, 'smoked salmon'), (6, 'cod'), (6, 'tilapia'), (6, 'tuna steak'),
(6, 'whitefish'), (6, 'halibut'), (6, 'trout'), (6, 'red snapper'), (6, 'sea bass'),
(6, 'fish fillets'), (6, 'shrimp'), (6, 'prawns'), (6, 'crab'), (6, 'scallop'),
(6, 'mussel'), (6, 'clam'), (6, 'squid'), (6, 'nori'), (6, 'lobster');