-- Allergies
INSERT INTO preferences (name) VALUES ('Celery-free');
INSERT INTO preferences (name) VALUES ('Dairy-free');
INSERT INTO preferences (name) VALUES ('Fish-free');
INSERT INTO preferences (name) VALUES ('Lupine-free');
INSERT INTO preferences (name) VALUES ('Peanut-free');
INSERT INTO preferences (name) VALUES ('Shellfish-free');
INSERT INTO preferences (name) VALUES ('Tree-Nut-free');
INSERT INTO preferences (name) VALUES ('Crustacean-free');
INSERT INTO preferences (name) VALUES ('Egg-free');
INSERT INTO preferences (name) VALUES ('Gluten-free');
INSERT INTO preferences (name) VALUES ('Mustard-free');
INSERT INTO preferences (name) VALUES ('Sesame-free');
INSERT INTO preferences (name) VALUES ('Soy-free');
INSERT INTO preferences (name) VALUES ('Wheat-free');
-- Diets
INSERT INTO preferences (name) VALUES ('Alcohol-free');
INSERT INTO preferences (name) VALUES ('Balanced');
INSERT INTO preferences (name) VALUES ('High-Fiber');
INSERT INTO preferences (name) VALUES ('High-Protein');
INSERT INTO preferences (name) VALUES ('Keto');
INSERT INTO preferences (name) VALUES ('Kidney friendly');
INSERT INTO preferences (name) VALUES ('Kosher');
INSERT INTO preferences (name) VALUES ('Low-Carb');
INSERT INTO preferences (name) VALUES ('Low-Fat');
INSERT INTO preferences (name) VALUES ('Low potassium');
INSERT INTO preferences (name) VALUES ('Low-Sodium');
INSERT INTO preferences (name) VALUES ('No oil aded');
INSERT INTO preferences (name) VALUES ('No-sugar');
INSERT INTO preferences (name) VALUES ('Paleo');
INSERT INTO preferences (name) VALUES ('Pescatarian');
INSERT INTO preferences (name) VALUES ('Pork-free');
INSERT INTO preferences (name) VALUES ('Red meat-free');
INSERT INTO preferences (name) VALUES ('Sugar-conscious');
INSERT INTO preferences (name) VALUES ('Vegan');
INSERT INTO preferences (name) VALUES ('Vegetarian');
-- Nutrients Macronutrients
INSERT INTO preferences (name) VALUES ('Carbs');
INSERT INTO preferences (name) VALUES ('Fat');
INSERT INTO preferences (name) VALUES ('Fiber');
INSERT INTO preferences (name) VALUES ('Monounsaturated');
INSERT INTO preferences (name) VALUES ('Polyunsaturated');
INSERT INTO preferences (name) VALUES ('Protien');
INSERT INTO preferences (name) VALUES ('Sugars');
INSERT INTO preferences (name) VALUES ('Trans');
-- Nutrients Micronutrients
INSERT INTO preferences (name) VALUES ('Calcium');
INSERT INTO preferences (name) VALUES ('Cholesterol');
INSERT INTO preferences (name) VALUES ('Folate (Equivalent)');
INSERT INTO preferences (name) VALUES ('Iron');
INSERT INTO preferences (name) VALUES ('Magnesium');
INSERT INTO preferences (name) VALUES ('Niacin (B3)');
INSERT INTO preferences (name) VALUES ('Phosphorus');
INSERT INTO preferences (name) VALUES ('Potassium');
INSERT INTO preferences (name) VALUES ('Riboflavin(B2)');
INSERT INTO preferences (name) VALUES ('Sodium');
INSERT INTO preferences (name) VALUES ('Thiamin (B1)');
INSERT INTO preferences (name) VALUES ('Vitamin A');
INSERT INTO preferences (name) VALUES ('Vitamin B6');
INSERT INTO preferences (name) VALUES ('Vitamin B12');
INSERT INTO preferences (name) VALUES ('Vitamin C');
INSERT INTO preferences (name) VALUES ('Vitamin D');
INSERT INTO preferences (name) VALUES ('Vitamin E');
INSERT INTO preferences (name) VALUES ('Vitamin K');